# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('gene_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gene', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['gene', 'gene_id'],
                'db_table': 'Genes',
            },
        ),
        migrations.CreateModel(
            name='SNPs',
            fields=[
                ('snp_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('snp_check', models.IntegerField(default='')),
                ('rs', models.CharField(default='', max_length=20)),
                ('hgvs', models.CharField(default='', max_length=20)),
                ('freq', models.CharField(default='', max_length=200)),
                ('ss', models.CharField(default='', max_length=100)),
                ('ss_proj', models.CharField(default='', max_length=200)),
                ('other2', models.CharField(default='', max_length=200)),
                ('action_to_take', models.CharField(default='', max_length=100)),
                ('check_by', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'SNPs',
            },
        ),
        migrations.RenameField(
            model_name='primers',
            old_name='primer_id',
            new_name='primerid',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='action_to_take',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='check_by',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='hgvs',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='other2',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='rs',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='snp_check',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='ss',
        ),
        migrations.RemoveField(
            model_name='primers',
            name='ss_proj',
        ),
        migrations.AddField(
            model_name='primers',
            name='end',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='primers',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='primers',
            name='start',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='anneal_temp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='primers',
            name='batch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='chrom',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='primers',
            name='direction',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='primers',
            name='exon',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='primers',
            name='frag_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='primers',
            name='gene',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='primers',
            name='m13_tag',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='primers',
            name='no_snps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='primers',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='primers',
            name='other',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='primers',
            name='primer_seq',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='primers',
            name='version',
            field=models.IntegerField(),
        ),
    ]
